# Generated by Django 4.1.2 on 2022-10-31 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currently_working', models.BooleanField()),
                ('description', models.CharField(max_length=2000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('title_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.career')),
            ],
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.university')),
            ],
        ),
        migrations.CreateModel(
            name='PersonStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.person')),
                ('study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.studies')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.socialmedia')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=5)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.languages')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.person')),
            ],
        ),
    ]
