# Generated by Django 4.1.2 on 2022-10-31 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='title_name',
        ),
    ]
