# Generated by Django 4.1.2 on 2022-11-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_remove_university_title_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studies',
            name='title_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_app.career'),
        ),
    ]
