# Generated by Django 4.1.2 on 2022-11-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0005_rename_study_id_personstudies_study_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='value',
        ),
        migrations.AddField(
            model_name='personmedia',
            name='value',
            field=models.CharField(default='sbuitragoo', max_length=30),
        ),
    ]
