# Generated by Django 4.1.2 on 2022-11-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0006_remove_socialmedia_value_personmedia_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='position',
            field=models.CharField(default='Engineer', max_length=100),
            preserve_default=False,
        ),
    ]
